const students = [
	{ id: 2, name: "Alexander", image: "assets/images/students/alexander_kallin.jpg" },
	{ id: 4, name: "Anna", image: "assets/images/students/anna_persson.jpg" },
	{ id: 5, name: "Dexter", image: "assets/images/students/dexter_cerdic_wall.jpg" },
	{ id: 6, name: "Fredrik", image: "assets/images/students/fredrik_wiking.jpg" },
	{ id: 7, name: "Gustav", image: "assets/images/students/gustav_zimmer.jpg" },
	{ id: 9, name: "Isra", image: "assets/images/students/isra_saleh.jpg" },
	{ id: 11, name: "Katarina", image: "assets/images/students/katarina_sjolin.jpg" },
	{ id: 12, name: "Leo", image: "assets/images/students/leo_zarazaga.jpg" },
	{ id: 13, name: "Lisa", image: "assets/images/students/lisa_maliqi.jpg" },
	{ id: 14, name: "Louise", image: "assets/images/students/louise_bosson.jpg" },
	{ id: 16, name: "Lucas H.", image: "assets/images/students/lucas_hernandez.jpg" },
	{ id: 18, name: "Lukas S.", image: "assets/images/students/lukas_sandborgh.jpg" },
	{ id: 19, name: "Madeleine", image: "assets/images/students/madeleine_persson.jpg" },
	{ id: 20, name: "Magnus", image: "assets/images/students/magnus_lundberg.jpg" },
	{ id: 21, name: "Maa (Simo)", image: "assets/images/students/maa_al_samaa_souaidan.jpg" },
	{ id: 22, name: "Marsel", image: "assets/images/students/marsel_shaykhutdinov.jpg" },
	{ id: 23, name: "Mats", image: "assets/images/students/mats_eksten.jpg" },
	{ id: 24, name: "Natalia", image: "assets/images/students/natalia_iancovscaia.jpg" },
	{ id: 26, name: "Oktavian", image: "assets/images/students/oktavian_paunku.jpg" },
	{ id: 27, name: "Olle", image: "assets/images/students/olle_wistedt.jpg" },
	{ id: 28, name: "Patrik", image: "assets/images/students/patrik_norrgard.jpg" },
	{ id: 29, name: "Philip", image: "assets/images/students/philip_andersson.jpg" },
	{ id: 30, name: "Rami", image: "assets/images/students/rami_jundi.jpg" },
	{ id: 31, name: "Sally", image: "assets/images/students/sally_engstrom_apelmo.jpg" },
	{ id: 32, name: "Sarah", image: "assets/images/students/sarah_emilsson.jpg" },
	{ id: 33, name: "Sebastian", image: "assets/images/students/sebastian_ekstrom.jpg" },
	{ id: 34, name: "Teddie", image: "assets/images/students/teddie_finstrom.jpg" },
	{ id: 35, name: "Tilde", image: "assets/images/students/tilde_tarkiainen_ljungquist.jpg" },
	{ id: 36, name: "Tristan", image: "assets/images/students/tristan_flink.jpg" },
];

const missing_students = [
	{ id: 1, name: "Abdirahman", image: "assets/images/students/abdirahman_hersi.jpg" },
	{ id: 3, name: "Anastasios", image: "assets/images/students/anastasios_roupelas.jpg" },
	{ id: 8, name: "Hassan", image: "assets/images/students/hassan_ayyan.jpg" },
	{ id: 10, name: "Kasper", image: "assets/images/students/kasper_akegardh.jpg" },
	{ id: 15, name: "Louissa", image: "assets/images/students/louissa_shrif.jpg" },
	{ id: 17, name: "Ludvig", image: "assets/images/students/ludvig_enger.jpg" },
	{ id: 25, name: "Nicole", image: "assets/images/students/nicole_rozanska.jpg" },
];
